name = "Loom"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Loom", "CaseStudies"]

[[lean_lib]]
name = "CaseStudies"

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.23.0"

[[require]]
name = "auto"
scope = "leanprover-community"
rev = "2c088e7617d6e2018386de23b5df3b127fae4634"


[[lean_lib]]
name = "Loom"
